server:
  port: 8888
  address: 127.0.0.1
  context-path: /sakura

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: utf-8
    enabled: true

  profiles:
    active: dev

prefix:
  readTimeout: 6000
  connectTimeout: 6000
